version: '3.8'

services:
  storage-api:
    container_name: storage-api
    build:
        dockerfile: Dockerfile
        context: .
        target: development
    privileged: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - storage-postgres
      - storage-redis
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - storage-api-network
    command: yarn start:dev

  storage-postgres:
    image: postgres:latest
    container_name: storage-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - storage-api-network
    ports:
      - "5432:5432"

  storage-redis:
    image: redis:alpine
    container_name: storage-redis
    ports:
      - "6379:6379"
    networks:
      - storage-api-network
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  storage-api-network:
    driver: bridge
    name: storage-api-network
